// 3ColumnPreview/src/components/card/card.jsx
import React from "react";
import styles from './card.scss';

export const Card = (props) => {

   return <div className="card-container" style={{backgroundColor: props.color}}>
            <img src={props.image} />
            <h2>{props.title}</h2>
            <p>{props.text}</p>
            <button style={{color: props.color}}>Learn More</button>
          </div>;
}

// 3ColumnPreviewCard/src/app/components/card/card.component.ts
import { Component, Input as CardInput } from '@angular/core';
import { Card } from 'src/app/models/card';

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.scss']
})
export class CardComponent {

  @CardInput({required: true}) card: Card = new Card();


}

<div class="card-container" [style.--bgColor]="card.color">
  <img [src]="card.image" alt="Image">
  <h1>{{ card.title | upperCustom }}</h1>
  <p>{{ card.description }}</p>
  <button>Learn More</button>
</div>
