// FourCardFeature/src/app/components/body/card/card.component.ts
import { Component, Input as CardInput } from '@angular/core';
import { Card } from 'src/app/shared/models/card.model';

@Component({
  selector: 'app-card',
  templateUrl: './card.component.html',
  styleUrls: ['./card.component.scss']
})
export class CardComponent {

  @CardInput() card = new Card();

}

<div class="card-container" [style.--color]="card.color">
  <h4 class="card-title">{{ card.title }}</h4>
  <p class="card-description">{{ card.description }}</p>
  <img class="card-image" src="../../../../assets/{{ card.image }}" alt="Image">
</div>

// FourCard/src/components/card/card.jsx
import React from "react";
import styles from './card.scss';
import { darken } from '@material-ui/core/styles';

export const Card = (props) => {

  const cardColor = darken(props.color, 0);

   return <div className="card-container" style={{borderTop: '3px solid ' + props.color}}>
            <div className="card-text">
              <div className="card-content">
              <h1 className="card-title">{props.title}</h1>
              <p className="card-body">{props.body}</p>
              <img src={props.image} alt="Image" />
            </div>
            </div>
          </div>;

}
